kumuluzee:
  name: dostavca-profile
  env:
    name: dev
  version: 1.0.0
  server:
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  metrics:
    servlet:
      mapping: /metrics
is_running: false